import { useState } from 'react';
import { Bell, CloudRain, Droplets, LogOut, MapPin, ShieldAlert, Thermometer, Wind } from 'lucide-react';
import { alerts, counties, weatherTrend } from '../data/mockData';
import type { SessionUser } from '../App';

export default function FarmerDashboard({ user, onSignOut }: { user: SessionUser; onSignOut: () => void }) {
  const [showAll, setShowAll] = useState(false);
  const county = counties.find((item) => item.name === user.county) ?? counties.find((item) => item.name === 'Kisumu')!;
  const localAlerts = alerts.filter((item) => item.countyId === county.id && item.status !== 'resolved');
  const visibleAlerts = showAll ? alerts.filter((item) => item.status !== 'resolved') : localAlerts;
  return <main className="min-h-screen bg-[#F6F7F4] pb-8 text-[#14201A]">
    <header className="sticky top-0 z-10 border-b border-[#DDE5DE] bg-white/95 px-4 py-3 backdrop-blur sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between"><div className="flex items-center gap-2.5"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#0E7C5A] text-sm font-bold text-white">M</div><div><p className="font-display text-[15px] font-bold leading-tight">MalariaWatch</p><p className="flex items-center gap-1 text-[11px] text-[#55665C]"><MapPin size={11} /> {user.county ?? county.name}</p></div></div><button type="button" onClick={onSignOut} className="inline-flex items-center gap-1.5 rounded-lg border border-[#DCE2DB] px-3 py-2 text-xs font-bold text-[#55665C] hover:bg-[#F6F7F4]"><LogOut size={14} /> <span className="hidden sm:inline">Log out</span></button></div></header>
    <div className="mx-auto max-w-6xl px-4 py-5 sm:px-8 sm:py-8"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.08em] text-[#0A5A41]">Farmer dashboard</p><h1 className="mt-1 font-display text-2xl font-bold sm:text-3xl">Good morning, {user.name.split(' ')[0]}</h1><p className="mt-1 text-sm text-[#55665C]">Local conditions and early warnings for your farm.</p></div>
      <section className="rounded-2xl bg-[#0D2A20] p-5 text-white shadow-sm sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.08em] text-[#9BC9AE]">Current county risk</p><p className="mt-2 font-display text-3xl font-bold">{county.risk === 'critical' ? 'Critical' : county.risk === 'alert' ? 'Alert' : county.risk === 'watch' ? 'Watch' : 'Low'}</p><p className="mt-1 text-sm text-[#C5D8CB]">{county.name} · updated {county.lastUpdated}</p></div><div className="rounded-xl bg-[#B23434] p-3"><ShieldAlert size={24} /></div></div><div className="mt-5 grid grid-cols-3 gap-2 border-t border-[#315144] pt-4 text-center"><div><p className="text-lg font-bold">{county.rainfall7d}mm</p><p className="text-[11px] text-[#B9C7BE]">Rainfall / 7 days</p></div><div><p className="text-lg font-bold">{county.tempAvg}°C</p><p className="text-[11px] text-[#B9C7BE]">Avg temperature</p></div><div><p className="text-lg font-bold">{county.humidity}%</p><p className="text-[11px] text-[#B9C7BE]">Humidity</p></div></div></section>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><section className="rounded-2xl border border-[#E2E6DE] bg-white p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-display text-base font-bold">Early warnings</h2><p className="mt-1 text-xs text-[#55665C]">Alerts from weather and health surveillance teams.</p></div><Bell size={18} className="text-[#B23434]" /></div>{visibleAlerts.length ? <div className="mt-4 space-y-3">{visibleAlerts.map((alert) => <article key={alert.id} className="rounded-xl border border-[#F0D5D0] bg-[#FFF8F7] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-[#7A2828]">{alert.level === 'critical' ? 'Critical malaria risk' : 'Malaria risk alert'} · {alert.ward}</p><p className="mt-1 text-xs leading-5 text-[#55665C]">{alert.indicators[0]}</p></div><span className="shrink-0 rounded-full bg-[#FAE1DE] px-2 py-1 text-[10px] font-bold uppercase text-[#B23434]">{alert.confidence}</span></div><p className="mt-3 text-xs font-semibold text-[#3D4D44]">Recommended: {alert.recommendedActions[0]}</p></article>)}</div> : <p className="mt-5 rounded-xl bg-[#F3FAF5] p-4 text-sm text-[#0A5A41]">No active alerts in {county.name}. Keep monitoring local conditions.</p>}{!showAll && <button type="button" onClick={() => setShowAll(true)} className="mt-4 text-xs font-bold text-[#0A5A41]">View regional alerts</button>}</section>
        <section className="rounded-2xl border border-[#E2E6DE] bg-white p-5"><h2 className="font-display text-base font-bold">Today’s weather</h2><p className="mt-1 text-xs text-[#55665C]">Forecast signals for planning farm work.</p><div className="mt-5 grid grid-cols-2 gap-3"><Metric icon={<CloudRain size={16} />} label="Rainfall" value={`${weatherTrend.rainfall.at(-1)} mm`} /><Metric icon={<Thermometer size={16} />} label="Temperature" value={`${weatherTrend.temperature.at(-1)}°C`} /><Metric icon={<Droplets size={16} />} label="Humidity" value={`${county.humidity}%`} /><Metric icon={<Wind size={16} />} label="Wind" value="Light" /></div><div className="mt-5 rounded-xl bg-[#F3FAF5] p-4"><p className="text-xs font-bold text-[#0A5A41]">Farm action</p><p className="mt-1 text-xs leading-5 text-[#55665C]">Check standing water after rainfall and report unusual mosquito activity to your local health team.</p></div></section></div>
      <section className="mt-5 rounded-2xl border border-[#E2E6DE] bg-white p-5"><h2 className="font-display text-base font-bold">Health surveillance snapshot</h2><p className="mt-1 text-xs text-[#55665C]">Latest county reports from participating facilities.</p><div className="mt-4 grid grid-cols-3 gap-3"><Metric label="Suspected" value={county.suspected.toLocaleString()} /><Metric label="Tested" value={county.tested.toLocaleString()} /><Metric label="Positive" value={county.positive.toLocaleString()} /></div><p className="mt-4 text-xs text-[#55665C]">If someone has fever, seek testing at the nearest health facility promptly.</p></section>
    </div></main>;
}

function Metric({ icon, label, value }: { icon?: React.ReactNode; label: string; value: string }) { return <div className="rounded-xl bg-[#F6F7F4] p-3"><div className="flex items-center gap-1.5 text-[#0E7C5A]">{icon}<span className="text-[11px] font-semibold text-[#55665C]">{label}</span></div><p className="mt-1 font-display text-lg font-bold">{value}</p></div>; }